In [1]:
import os
import pandas as pd
import pyarrow
import fastparquet
import glob

In [2]:
files_path = glob.glob("./dataset/raw/*.snappy.parquet")
files_path

['./dataset/raw\\part-00000-tid-2779033056155408584-f6316110-4c9a-4061-ae48-69b77c7c8c36-4-1-c000.snappy.parquet',
 './dataset/raw\\part-00000-tid-5196563791502273604-c90d3a24-52f2-4955-b4ec-fb143aae74d8-4-1-c000.snappy.parquet',
 './dataset/raw\\part-00000-tid-6364321654468257203-dc13a5d6-36ae-48c6-a018-37d8cfe34cf6-263-1-c000.snappy.parquet']

In [3]:
df = pd.read_parquet(files_path[2], engine="fastparquet")

In [4]:
df

,produto,categoria,descricao,tipos,label,subcategoria,marca,fabricante
0,69753381296344216,Package,MONDAY NIGHT BREW DON'T CALL IT HOTLANTA 6/4/1...,Package,In&Out,Red Wine,Monday Night Don't Call It Hotlanta,Monday Night Brewing
1,5019314249828979377,Distilled Spirits,BARRELL V907 RED PHONE BOOTH & TOWER,Distilled Spirits,Specialty,Lager / Pilsner,Barrell Bourbon- Private Label,Barrell Craft Spirits
2,4016404282141162328,Distilled Spirits,DRINKWORKS SIMPLY REFRESHING GIN & TONIC 12/4/...,Distilled Spirits,Core,Lager,Drinkworks Simply Refreshing Gin & Tonic,AB Drinkworks
3,6217366559810422145,Distilled Spirits,CENZON REPOSADO 100% AGAVE 6/750ML 80PF,Distilled Spirits,None,Lager,Cenzon Reposado 100% Agave Tequila,Sazerac Spirits
4,7356488787409434558,Draft,REFORMATION STARK 1/4 KEG,Draft,Core,Red Wine,Reformation Stark,Reformation Brewery
...,...,...,...,...,...,...,...,...
192356311,2910976334046702887,ABA Spirits,SAZERAC OLD WESTBURY GIN WNBS 1LTR 42PRF,Wine > 14 %,Core,Lager,Old Westbury Extra Dry Gin,Sazerac ABA
192356312,997545005038320324,Package,TX RANCH WATER LIME 4/6 CN,Package,Core,Soda,TX Ranch Water Lime,MPL Brands NV/Patco
192356313,5342092316314076162,Draft,TANTRUM POEMS AT MIDNIGHT RASPBERRY BLACKBERRY...,Draft,Discontinued,Energy,Tantrum Poems at Midnight Raspberry Blackberry,Tantrum Brewing Co
192356314,8663495453589323322,Wine,SALVESTRIN RETTAGIO 2019,Wine > 14 %,Close Out,Lager,Salvestrin Rettagio,Salvestrin Wine Company
192356315,1933905639949913855,Distilled Spirits,STROUDWATER RYE,Distilled Spirits,Close Out,Lager,Stroudwater Rye,Northstar Brands

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 192356316 entries, 0 to 192356315
Data columns (total 8 columns):
 #   Column        Dtype
---  ------        -----
 0   produto       object
 1   categoria     object
 2   descricao     object
 3   tipos         object
 4   label         object
 5   subcategoria  object
 6   marca         object
 7   fabricante    object
dtypes: object(8)
memory usage: 11.5+ GB

In [8]:
df.isnull().sum()

produto                0
categoria              0
descricao              0
tipos                  0
label           39952179
subcategoria           0
marca                  0
fabricante             0
dtype: int64

In [9]:
df.notnull().sum()

produto         192356316
categoria       192356316
descricao       192356316
tipos           192356316
label           152404137
subcategoria    192356316
marca           192356316
fabricante      192356316
dtype: int64

In [6]:
num_duplicadas = df.duplicated().sum()
print("Número de linhas duplicadas:", num_duplicadas)

Número de linhas duplicadas: 192051360

In [8]:
print("Número de linhas unicas:", df.shape[0] - num_duplicadas)

Número de linhas unicas: 304956

In [11]:
df.columns

Index(['produto', 'categoria', 'descricao', 'tipos', 'label', 'subcategoria',
       'marca', 'fabricante'],
      dtype='object')

In [12]:
df.nunique()

produto         7092
categoria          7
descricao       7092
tipos             22
label             14
subcategoria      43
marca           4221
fabricante       343
dtype: int64

In [17]:
df['categoria'].unique().tolist()

['Package',
 'Distilled Spirits',
 'Draft',
 'Wine',
 'Non-Alcohol',
 'ABA Spirits',
 'Tobacco']

In [10]:
df_clean = df.drop_duplicates(subset=["produto"])
df_clean

,produto,categoria,descricao,tipos,label,subcategoria,marca,fabricante
0,69753381296344216,Package,MONDAY NIGHT BREW DON'T CALL IT HOTLANTA 6/4/1...,Package,In&Out,Red Wine,Monday Night Don't Call It Hotlanta,Monday Night Brewing
1,5019314249828979377,Distilled Spirits,BARRELL V907 RED PHONE BOOTH & TOWER,Distilled Spirits,Specialty,Lager / Pilsner,Barrell Bourbon- Private Label,Barrell Craft Spirits
2,4016404282141162328,Distilled Spirits,DRINKWORKS SIMPLY REFRESHING GIN & TONIC 12/4/...,Distilled Spirits,Core,Lager,Drinkworks Simply Refreshing Gin & Tonic,AB Drinkworks
3,6217366559810422145,Distilled Spirits,CENZON REPOSADO 100% AGAVE 6/750ML 80PF,Distilled Spirits,None,Lager,Cenzon Reposado 100% Agave Tequila,Sazerac Spirits
4,7356488787409434558,Draft,REFORMATION STARK 1/4 KEG,Draft,Core,Red Wine,Reformation Stark,Reformation Brewery
...,...,...,...,...,...,...,...,...
183536372,8225211493147767417,Wine,SANS WINE CO. - POOR RANCH VINEYARDS ROSE OF C...,Wine < 14 %,Discontinued,Lager,Poor Ranch Vineyards Rose Of Carignan,Sans Wine Company
183536373,5759670436535233385,Distilled Spirits,MR BOSTON BLUE CURACAO 12/1L 30PF,Distilled Spirits,None,Lager,Mr. Boston Blue Curacao Liqueur,Sazerac Spirits
183536374,6964240149904972585,Distilled Spirits,PAUL MASSON PEACH BRANDY 6/1.75L 54PF,Distilled Spirits,None,Lager,Paul Masson Peach Brandy,Sazerac Spirits
183536375,4616112300817630028,Distilled Spirits,SKOL GOLD RUM 12/1L 80PF,Distilled Spirits,None,Other Package,Skol Gold Rum,Sazerac Spirits
183536376,7531212314911361188,Distilled Spirits,CONCANNON IRISH WHISKEY 6/750ML 80PF,Distilled Spirits,None,Other Package,Concannon Irish Whiskey,Sazerac Spirits

In [11]:
df_clean.to_parquet('./dataset/processed/produto.parquet', engine='pyarrow', index=False)